### ISSUE TITLE
Contribution: Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by MaxMorais** [undb-io/undb#1179]
Hi Guys! Chers from Brazil!

First of all, I would like to congrats the team, for the amazing product!

I have found it past week, and I had to give it a try!
In almost minutes, I had a demo instance working for me.

So, I decided to work around Brazilian Portuguese Translation!

My changes are here: https://github.com/MaxMorais/undb/tree/develop-pt-BR, I'll fix some bugs and give it back to the community!

Things I found during that process, that you may will need to take a look on the future, when more localization happens!

- [ ] Numbers should be localized, eg: 1.234,0232
- [ ] Currency should be localized, not only in the Currency symbol, but also as formating eg: R$ 1.234,34
- [ ] Other datetime formats should be added, like 23/09/2023 (dd/MM/YYYY)
- [ ] Translation should follow more the concept of tokens instead of strings eg: `USER_INVALID`: 'This username is invalid'
 
Except of that, guys, you rocks!
The work you are doing is amazing!

I wanna see what this product will be on the next months!

All the best!

**Comment by nichenqin** [comment]
thanks!

**Comment by nichenqin** [comment]
Brazilian Portuguese has been added
