### ISSUE TITLE
🐛 [BUG] - CSV upload drag-drop cursor css

### ISSUE THREAD

**Issue by octoshrimpy** [undb-io/undb#1313]
### Description

over the centered image within the drag-drop box, the cursor does not have the "click-point" cursor, but it does if you hover outside, see recording. The offending item is the label.

https://github.com/undb-xyz/undb/assets/7097172/bc32bb8e-40d4-4e49-892f-64feb75e9ee2

### Reproduction steps

```bash
.
```

**Comment by nichenqin** [comment]
Looks like a `flowbite` bug, will try to patch it
