### ISSUE TITLE
🐛 [BUG] - Filtering Dates

### ISSUE THREAD

**Issue by CarefulGuru** [undb-io/undb#1545]
### Description

I'm trying to filter by a date column in a grid. I have multiple items where the date is 2023-05-25. When I filter by Date is Equal to 2023-05-25, it doesn't filter, just returns an empty grid. Can provide access to the instance if needed. 

Also, if I select a date (2023-08-25) and click apply, it ends up choosing 2023-08-24. See video below

https://github.com/undb-xyz/undb/assets/141072854/88724c27-d950-45c3-9501-f0172f22ff5b

### Reproduction steps

```bash
1. Go to a table with a Date column
2. Click on Filter
3. Choose the Date column, and the "equal" to option
4. Select a date that exists in the table
5. See error.
```

### Browsers

Chrome

**Comment by nichenqin** [comment]
because date is filter by million second, will have a look
