### ISSUE TITLE
[feature]: 表格授权

### ISSUE THREAD

**Issue by ptn8hi** [undb-io/undb#1809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

我用docker部署了一版，发现注册用户默认对所有表都是管理员权限，从数据安全角度来看是不是不大合理？能否修改为只有拥有者邀请后才具备查看以上的权限？

### Why should this be worked on?

或者是否可以通过环境变量或增加系统管理员角色来配置相关内容？

**Comment by nichenqin** [comment]
可以现在在重构
