### ISSUE TITLE
🐛 [BUG] - 文档和演示环境挂了

### ISSUE THREAD

**Issue by meimosor** [undb-io/undb#1857]
### Description

文档和演示环境挂了

### Reproduction URL

https://demo.undb.xyz/

### Reproduction steps

```bash
1. Go to '...'
https://demo.undb.xyz/
2. See error: ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

### Browsers

Chrome

**Comment by nichenqin** [comment]
现在在重构原来的域名不用了

**Comment by meimosor** [comment]
建议放个roadmap
