### ISSUE TITLE
🐛 [BUG] - button which redirects to undb cloud is'nt working

### ISSUE THREAD

**Issue by VikramNagwal** [undb-io/undb#1991]
### Description

The button on the homepage that redirects to the undb Cloud is not functioning properly (it is not redirecting to the intended destination).

video: 

https://github.com/user-attachments/assets/315c3bea-eadd-43a3-8bcd-15b565011c0f

### Reproduction steps

```bash
1. Go to 'https://undb.io/'
2. Click on 'try undb cloud for free' Button
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Firefox

**Comment by nichenqin** [comment]
thanks!
