### ISSUE TITLE
🐛 [BUG] - Developer API View

### ISSUE THREAD

**Issue by patricklenert** [undb-io/undb#2079]
### Description

![image](https://github.com/user-attachments/assets/1d52c9b6-386f-41b5-96ef-0428b4e41e1f)

The Developer > OpenAPI View is broken. 

### Reproduction steps

```bash
1. Go to 'Your Base'
2. Click on 'Your table'
3. Click on 'Developer'
4. Click on 'OpenAPI'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by nichenqin** [comment]
fixed
