### ISSUE TITLE
🐛 [BUG] - UNDB_DISABLE_REGISTRATION breaks invites

### ISSUE THREAD

**Issue by MerlinB** [undb-io/undb#2132]
### Description

Not sure if this is intended but when registration is disabled using `UNDB_DISABLE_REGISTRATION`, it is still possible to send out invites but as sign up is disabled, invited user cannot accept the invite and complete the signup. It would be very useful to be able to just disable public registration but allow signup via invites.

### Reproduction steps

```bash
1. Enable `UNDB_DISABLE_REGISTRATION`
2. Invite user
3. User goes to invite link - blank page
```

**Comment by nichenqin** [comment]
fixed
