### ISSUE TITLE
[feature]: Allow References across Bases

### ISSUE THREAD

**Issue by MerlinB** [undb-io/undb#2133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would be nice to allow foreign keys across different bases in the same space.

### Why should this be worked on?

Bases are a good way to logically separate data but that doesn't mean that it won't be related. I might have a base for company internals and one for a project, where I want to reference employees of the company.

**Comment by nichenqin** [comment]
This feature has been implemented since v1.0.0-126
