### ISSUE TITLE
🐛 [BUG] - Report creation - Optional number field treated as required

### ISSUE THREAD

**Issue by MerlinB** [undb-io/undb#2134]
### Description

Despite being defined and shown as optional, a record wont be created unless the value is filled in. In my case the number field had min and max set. 

Additionally, in the creation form, editing the optional number field and then deleting the value inside will set it to 0, instead of undefined, as indicated by the console log.

### Reproduction steps

```bash
1. Create an optional number field, set min and max values
2. Open Record creation modal, leave the field empty
3. Click "Create"
4. Form is reset, no error, nothing else happens
5. Fill in the optional number field
6. Submit form
7. Record is created
```

### Logs

```bash
No relevant logs
```

**Comment by nichenqin** [comment]
fixed : )
