### ISSUE TITLE
🐛 [BUG] - Table Sort: Fields not selectable despite being sortable

### ISSUE THREAD

**Issue by MerlinB** [undb-io/undb#2180]
### Description

The sort selector is missing all but one field, despite sortable fields being available, like a required integer column.

<img width="1083" alt="Screenshot 2024-11-11 at 3 08 10 PM" src="https://github.com/user-attachments/assets/c0724192-ec42-46cc-b4e0-7c6369350ad1">

### Reproduction steps

```bash
1. Create a table with a required integer column
2. Try to create a sort
```

### Logs

```bash
No relevant warnings or errors
```

**Comment by nichenqin** [comment]
fixed

**Comment by MerlinB** [comment]
Thank you for the quick fix, as always.
