### ISSUE TITLE
🐛 [BUG] - Kanban creation: No kanban field selectable

### ISSUE THREAD

**Issue by MerlinB** [undb-io/undb#2181]
### Description

Similar to https://github.com/undb-io/undb/issues/2180.
No kanban field can be selected when trying to create a Kanban view despite a required, single-select column existing.
<img width="463" alt="Screenshot 2024-12-07 at 3 25 05 PM" src="https://github.com/user-attachments/assets/282b6563-5bcb-491d-8edc-62a1bde49510">

### Reproduction steps

```bash
1. Create table with select column
2. Try to create a Kanban view
```

**Comment by nichenqin** [comment]
To fully resolve this issue, some refactoring work is required. As a fallback approach, I chose to allow the creation of a view in the navigation list on the left without requiring field selection. After the view is created, users can configure the fields later.

**Comment by nichenqin** [comment]
Fields can be selected in the top header.

**Comment by MerlinB** [comment]
Thank you, that works!
