### ISSUE TITLE
[feature]: Hope to support Simplified Chinese

### ISSUE THREAD

**Issue by xiahao90** [undb-io/undb#2182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hope to support Simplified Chinese

### Why should this be worked on?

Hope to support Simplified Chinese

**Comment by nichenqin** [comment]
It's already supported, you can click your avatar menu to toggle language
<img width="567" alt="image" src="https://github.com/user-attachments/assets/aa39c5df-cecc-4eb8-9ad4-39d29e7a4f57" />

**Comment by xiahao90** [comment]
👍
