### ISSUE TITLE
[feature]: How Docker achieves data persistence

### ISSUE THREAD

**Issue by xiahao90** [undb-io/undb#2185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

How Docker achieves data persistence

### Why should this be worked on?

How Docker achieves data persistence

**Comment by nichenqin** [comment]
you can add volume to `undb.sqlite` file

```bash
docker run -d \
  -p 3721:3721 \
  -v $(pwd)/undb.sqlite:/usr/src/app/undb.sqlite \
  -v $(pwd)/undb:/usr/src/app/undb \
  --name undb \
  your-image-name
```
