### ISSUE TITLE
🐛 [BUG] - select  error

### ISSUE THREAD

**Issue by xiahao90** [undb-io/undb#2186]
### Description

Unable to use selelct correctly, input is 111, result is still option1

https://github.com/user-attachments/assets/d8b41e42-9efb-48c5-b04e-78b96baacd8a

### Reproduction steps

```bash
1. https://app.undb.io/
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by nichenqin** [comment]
fixed
